apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-extended.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: authorization-pgadmin
  name: authorization-pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: authorization-pgadmin
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-extended.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: authorization-pgadmin
    spec:
      containers:
        - env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@mail.ru
            - name: PGADMIN_DEFAULT_PASSWORD
              value: 1qaz2wsx
          image: dpage/pgadmin4
          name: pgadmin4-container
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
