apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: authorization-api
  name: authorization-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: authorization-api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: authorization-api
    spec:
      containers:
        - env:
            - name: ConnectionStrings__DefaultConnection
              value: Host=authorization-db; Port=5454; Database=Authorization; Username=Authorization; Password=1qaz2wsx
            - name: EmailSettings__EmailAddress
              value: aidimir1@mail.ru
            - name: EmailSettings__EmailPassword
              value: ekRcm4JC5uqAtfam2naG
            - name: JwtSettings__Key
              value: 9kNih2ddBJI4W9ouHICafJ/d/SgYaq0OmK/5OeN0Nqs=
          image: authorization-api
          imagePullPolicy: Never
          name: authorization-api
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
