apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: authorization-db
  name: authorization-db
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "250m"
      storage: "512Mi"

